'use client';
import Link from 'next/link';
import type { Account } from '@/lib/types';
import { date, money } from '@/lib/format';
import { Badge, EmptyState, Icon } from './ui';
import s from './portal.module.css';
export default function AccountsTable({accounts, compact = false}: {accounts: Account[]; compact?: boolean}) {
  if (!accounts.length) return <EmptyState title="No hay cuentas en esta vista" description="Prueba con otros filtros o carga una cuenta para comenzar."/>;
  return <div className={s.tableWrap} tabIndex={0} role="region" aria-label="Tabla de cuentas hospitalarias"><table role="table" className={`${s.accountTable} ${compact ? s.compactTable : ''}`}><thead role="rowgroup"><tr role="row"><th role="columnheader" scope="col">Cuenta / referencia</th><th role="columnheader" scope="col">Aseguradora</th><th role="columnheader" scope="col" className={s.amountHeading}>Importe</th><th role="columnheader" scope="col">Preauditoría</th>{!compact && <th role="columnheader" scope="col">Estado</th>}<th role="columnheader" scope="col"><span className="sr-only">Ver detalle</span></th></tr></thead><tbody role="rowgroup">{accounts.map(account => <tr role="row" key={account.id}><td role="cell"><Link href={`/hospital/accounts/${account.id}`} className={s.accountIdentity}><span className={s.accountDocument} data-lane={account.lane}><Icon name="file" size={17}/></span><span><strong>{account.folio}</strong><small><span className={s.patientReference}>{account.patientReference}</span><time className={s.accountDate} dateTime={account.createdAt}>{date(account.createdAt)}</time></small></span></Link></td><td role="cell"><span className={s.insurerCell}>{account.insurer}</span></td><td role="cell" className={s.amountCell}>{money(account.total)}</td><td role="cell"><Badge lane={account.lane}/>{account.anomalyCount > 0 && <small className={s.findings}>{account.anomalyCount === 1 ? '1 hallazgo' : `${account.anomalyCount} hallazgos`}</small>}</td>{!compact && <td role="cell"><Badge status={account.status}/></td>}<td role="cell"><Link href={`/hospital/accounts/${account.id}`} className={s.tableOpen} aria-label={`Abrir cuenta ${account.folio}`}><Icon name="arrow" size={17}/></Link></td></tr>)}</tbody></table></div>;
}
