'use client';
import Link from 'next/link';
import { useState, type FormEvent } from 'react';
import { download, patch, post, useResource } from '@/lib/api';
import { actionText, date, money, number } from '@/lib/format';
import type { AccountDetail as Detail, AccountLine } from '@/lib/types';
import { useUser } from './auth';
import EvaluationHistory from './evaluation-history';
import { Badge, Button, EmptyState, ErrorState, Field, Icon, Loading, Modal, PageTitle, useToast } from './ui';

type Action = 'ready' | 'send' | 'outcome' | null;
export default function AccountDetail({id}: {id: string}) {
  const user = useUser(); const toast = useToast(); const {data, setData, error, loading, reload} = useResource<Detail>(`/accounts/${id}`);
  const [tab, setTab] = useState('lines'); const [lineFilter, setLineFilter] = useState('ALL'); const [lineSearch, setLineSearch] = useState('');
  const [busy, setBusy] = useState(''); const [editing, setEditing] = useState<AccountLine | null>(null); const [action, setAction] = useState<Action>(null);
  const [formError, setFormError] = useState(''); const [needsEvaluation, setNeedsEvaluation] = useState(false);
  const canReview = ['HOSPITAL_ADMIN', 'REVIEWER'].includes(user.role);
  const canSend = ['HOSPITAL_ADMIN', 'BILLING'].includes(user.role);
  const canExport = ['HOSPITAL_ADMIN', 'BILLING', 'REVIEWER'].includes(user.role);
  async function mutate(endpoint: string, extra: Record<string, unknown> = {}) {
    if (!data) return; setBusy(endpoint); setFormError('');
    try {const updated = await post<Detail>(`/accounts/${id}/${endpoint}`, {version: data.version, ...extra}); setData(updated); setAction(null); if(endpoint === 'evaluate') setNeedsEvaluation(false); toast(endpoint === 'claim' ? 'La cuenta quedó asignada a tu revisión.' : endpoint === 'evaluate' ? 'Evaluación actualizada con el convenio de la cuenta.' : 'La cuenta se actualizó correctamente.');}
    catch (e) {const message = e instanceof Error ? e.message : 'No se pudo actualizar la cuenta.'; setFormError(message); toast(message, 'error');}
    finally {setBusy('');}
  }
  async function saveLine(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!editing || !data) return; const form = new FormData(event.currentTarget); setBusy('line'); setFormError('');
    try { const updated = await patch<Detail>(`/accounts/${id}/lines/${editing.id}`, {version: data.version, quantity: Number(form.get('quantity')), unitPrice: Number(form.get('unitPrice')), justification: String(form.get('justification')).trim(), removed: form.get('removed') === 'on'}); setData(updated); setEditing(null); setNeedsEvaluation(true); toast('Corrección guardada. Reevalúa la cuenta para actualizar sus resultados.'); }
    catch (e) {setFormError(e instanceof Error ? e.message : 'No se pudo guardar la corrección.');} finally {setBusy('');}
  }
  async function exportAccount(format: 'xlsx' | 'csv' | 'pdf') { if(!data) return; setBusy('export'); try {await download(`/accounts/${id}/export?format=${format}`, `${data.folio}.${format}`);toast('Archivo de la cuenta descargado.');} catch(e) {toast(e instanceof Error ? e.message : 'No se pudo exportar.', 'error');} finally {setBusy('');} }
  if (loading) return <Loading label="Abriendo la cuenta"/>;
  if (error || !data) return <ErrorState message={error || 'La cuenta no está disponible.'} retry={reload}/>;
  const open = !['READY', 'SENT', 'RESOLVED'].includes(data.status);
  const lines = data.lines.filter(line => (lineFilter !== 'ALERTS' || (line.reason && line.status !== 'REMOVED')) && `${line.code} ${line.description}`.toLowerCase().includes(lineSearch.toLowerCase()));
  const evaluation = data.evaluation;
  return <><Link href="/hospital/accounts" className="back-link">← Volver a cuentas</Link><PageTitle title={data.folio} description={`Referencia ${data.patientReference} · ${data.insurer}`}><Button variant="secondary" onClick={reload}><Icon name="refresh" size={16}/> Actualizar</Button>{canExport && ['READY', 'SENT', 'RESOLVED'].includes(data.status) && <Button variant="secondary" loading={busy === 'export'} onClick={() => exportAccount('xlsx')}><Icon name="download" size={17}/> Exportar Excel</Button>}{canExport && ['READY', 'SENT', 'RESOLVED'].includes(data.status) && <Button variant="secondary" loading={busy === 'export'} onClick={() => exportAccount('pdf')}><Icon name="download" size={17}/> Descargar PDF</Button>}{canReview && open && <Button loading={busy === 'claim'} disabled={Boolean(busy)} onClick={() => mutate('claim')}><Icon name="review" size={17}/>{data.assignedTo === user.id ? 'Revisión asignada a ti' : 'Tomar revisión'}</Button>}</PageTitle>
    <div className="account-statusbar"><div><Badge lane={data.lane}/><Badge status={data.status}/><span className="account-version">Versión {data.version}</span></div><span><Icon name="shield" size={16}/> Convenio v{evaluation?.agreementVersion || '—'} · Datos sintéticos</span></div>
    <div className="detail-summary-grid"><div className="panel detail-overview"><div className="panel-heading"><h2>Datos de la cuenta</h2><Icon name="accounts"/></div><dl className="detail-facts"><div><dt>Referencia de paciente</dt><dd>{data.patientReference}</dd></div><div><dt>Aseguradora</dt><dd>{data.insurer}</dd></div><div><dt>Ingreso</dt><dd>{date(data.admissionDate)}</dd></div><div><dt>Egreso</dt><dd>{date(data.dischargeDate)}</dd></div><div><dt>Póliza</dt><dd>{data.policyNumber || 'Sin información'}</dd></div><div><dt>Diagnóstico CIE-10</dt><dd>{data.diagnosis || 'Sin información'}</dd></div><div><dt>Responsable</dt><dd>{data.assignedTo === user.id ? 'Tú' : data.assignedTo ? 'Asignada a otro revisor' : 'Sin asignar'}</dd></div><div><dt>Recibida</dt><dd>{date(data.createdAt, true)}</dd></div></dl></div><div className="panel financial-panel"><div className="panel-heading"><div><h2>Estimación financiera</h2><p>Importes en MXN</p></div><Icon name="chart"/></div><div className="financial-total"><span>Total facturado</span><strong>{money(evaluation?.billedTotal ?? data.total)}</strong></div>{evaluation ? <><dl className="financial-breakdown"><div><dt>Estimado aseguradora</dt><dd>{money(evaluation.insurerEstimate)}</dd></div><div><dt>Estimado paciente</dt><dd>{money(evaluation.patientEstimate)}</dd></div><div><dt>Ajuste por tabulador</dt><dd>{money(evaluation.tariffAdjustment)}</dd></div><div><dt>Cargos excluidos</dt><dd>{money(evaluation.excludedTotal)}</dd></div><div className={Number(evaluation.unresolvedAmount) > 0 ? 'unresolved' : ''}><dt>Pendiente de aclarar</dt><dd>{money(evaluation.unresolvedAmount)}</dd></div></dl><details className="policy-breakdown"><summary>Ver deducible y coaseguro <Icon name="down" size={14}/></summary><dl><div><dt>Deducible aplicado</dt><dd>{money(evaluation.deductible)}</dd></div><div><dt>Coaseguro aplicado</dt><dd>{money(evaluation.coinsurance)}</dd></div><div><dt>Tasa de póliza</dt><dd>{data.policy ? `${number(Number(data.policy.coinsuranceRate) * 100)}%` : 'Sin confirmar'}</dd></div></dl></details></> : <p className="text-muted p-6">La evaluación aún no está disponible.</p>}<p className="financial-disclaimer">Estimación de preauditoría. Los ajustes contractuales no se asignan automáticamente al paciente.</p></div></div>
    {needsEvaluation && <div className="notice notice-warning"><Icon name="alert"/><p>Hay correcciones posteriores a la última evaluación. Reevalúa antes de preparar esta cuenta.</p>{canReview && <Button variant="secondary" loading={busy === 'evaluate'} onClick={() => mutate('evaluate')}>Reevaluar cuenta</Button>}</div>}
    <section className="panel detail-lines"><div className="account-tabs" role="tablist" aria-label="Información de la cuenta">{[{key:'lines',label:'Líneas de cargo',count:data.lines.length}, {key:'findings',label:'Hallazgos',count:evaluation?.findings.length || 0}, {key:'history',label:'Historial',count:data.history.length}].map(item => <button key={item.key} role="tab" aria-selected={tab === item.key} className={tab === item.key ? 'selected' : ''} onClick={() => setTab(item.key)}>{item.label}<span className="tab-count">{item.count}</span></button>)}<button role="tab" aria-selected={tab === 'evaluations'} className={tab === 'evaluations' ? 'selected' : ''} onClick={() => setTab('evaluations')}>Evaluaciones</button></div>
      {tab === 'lines' && <><div className="table-toolbar"><div className="search-input"><Icon name="search" size={17}/><input aria-label="Buscar línea de cargo" placeholder="Buscar código o descripción…" value={lineSearch} onChange={e => setLineSearch(e.target.value)}/></div><select value={lineFilter} onChange={e => setLineFilter(e.target.value)} aria-label="Filtrar líneas"><option value="ALL">Todos los cargos</option><option value="ALERTS">Solo con hallazgos</option></select><span className="text-sm text-muted">{lines.length} líneas</span></div><div className="table-scroll line-table-scroll" role="region" aria-label="Líneas de cargo de la cuenta" tabIndex={0}><table className="data-table line-table"><thead><tr><th>Cargo</th><th>Cantidad</th><th>Precio unitario</th><th>Importe</th><th>Revisión</th>{canReview && open && <th>Acción</th>}</tr></thead><tbody>{lines.map(line => <tr key={line.id} className={line.status === 'REMOVED' ? 'removed-line' : ''}><td><strong>{line.description}</strong><small className="table-subtext">{line.code} · {line.category}</small>{line.justification && <p className="line-justification">{line.justification}</p>}</td><td className="number-cell">{number(line.quantity)}</td><td className="number-cell">{money(line.unitPrice)}</td><td className="number-cell font-semibold">{money(line.total)}</td><td><span className={`badge ${line.status === 'REMOVED' ? 'badge-neutral' : line.reason ? 'badge-yellow' : 'badge-green'}`}>{line.status === 'REMOVED' ? 'Retirado' : line.reason ? 'Con hallazgo' : 'Sin alertas'}</span>{line.reason && <small className="line-reason">{line.reason}</small>}</td>{canReview && open && <td><button className="table-open" onClick={() => {setEditing(line);setFormError('');}} aria-label={`Corregir ${line.description}`}><Icon name="edit" size={17}/></button></td>}</tr>)}</tbody></table></div>{!lines.length && <EmptyState title="No hay líneas con estos filtros" description="Prueba otra búsqueda o muestra todos los cargos."/>}</>}
      {tab === 'findings' && <div className="findings-list">{evaluation?.findings.length ? evaluation.findings.map((finding, i) => <article key={`${finding.code}-${i}`} className="finding"><span className={`finding-icon ${finding.severity === 'HIGH' || finding.severity === 'RED' ? 'coral-bg' : 'amber-bg'}`}><Icon name="alert" size={19}/></span><div><strong>{finding.message}</strong><p>{finding.code.replaceAll('_', ' ')}{finding.lineId ? ` · Línea ${data.lines.find(line => line.id === finding.lineId)?.code || 'de la cuenta'}` : ' · Hallazgo de la cuenta'}</p></div>{Number(finding.amount) > 0 && <span className="finding-amount">{money(finding.amount)}</span>}</article>) : <EmptyState title="Sin hallazgos en esta evaluación" description="Las reglas aplicadas no detectaron alertas. La autorización corresponde a la aseguradora."/>}</div>}
      {tab === 'history' && <div className="history-list">{data.history.length ? data.history.map((item, i) => <article key={item.id || i}><span className="history-icon"><Icon name="clock" size={17}/></span><div><strong>{actionText(item.action)}</strong><p>{typeof item.detail === 'string' ? item.detail : 'Cambio registrado en la cuenta.'}</p><small>{item.actor} · {date(item.createdAt, true)}</small></div></article>) : <EmptyState title="Sin movimientos" description="Las acciones realizadas sobre la cuenta quedarán registradas."/>}</div>}
      {tab === 'evaluations' && <EvaluationHistory key={`${id}-${data.version}`} accountId={id} folio={data.folio}/>}
    </section>
    <div className="detail-actions"><div><Icon name="shield" size={18}/><p>La reevaluación conserva la versión del convenio.</p></div><div>{canReview && open && <><Button variant="secondary" loading={busy === 'evaluate'} disabled={Boolean(busy)} onClick={() => mutate('evaluate')}><Icon name="refresh" size={17}/> Reevaluar</Button><Button disabled={Boolean(busy) || needsEvaluation} onClick={() => {setAction('ready');setFormError('');}}>Preparar para envío <Icon name="arrow" size={17}/></Button></>}{canSend && data.status === 'READY' && <Button onClick={() => {setAction('send');setFormError('');}}>Registrar envío manual <Icon name="arrow" size={17}/></Button>}{canSend && data.status === 'SENT' && <Button onClick={() => {setAction('outcome');setFormError('');}}>Registrar respuesta <Icon name="check" size={17}/></Button>}{canExport && ['READY', 'SENT', 'RESOLVED'].includes(data.status) && <Button variant="secondary" onClick={() => exportAccount('csv')} loading={busy === 'export'}><Icon name="download" size={17}/> CSV</Button>}</div></div>
    <Modal open={Boolean(editing)} onClose={() => {if(!busy) setEditing(null);}} title="Revisar línea de cargo" description={editing?.description}>{editing && <form onSubmit={saveLine} key={editing.id}><div className="notice"><Icon name="review"/><p>La corrección debe conservar su motivo. Toma la revisión de la cuenta antes de modificarla.</p></div><div className="form-grid"><Field label="Cantidad" required><input name="quantity" type="number" step="0.001" min="0.001" defaultValue={editing.quantity} required/></Field><Field label="Precio unitario · MXN" required><input name="unitPrice" type="number" step="0.01" min="0" defaultValue={editing.unitPrice} required/></Field></div><Field label="Justificación del cambio" required hint="Describe el motivo. Evita nombres de pacientes y datos clínicos innecesarios."><textarea name="justification" rows={4} minLength={5} maxLength={2000} defaultValue={editing.justification || ''} placeholder="La cantidad se ajustó de acuerdo con…" required/></Field><label className="checkbox-label"><input name="removed" type="checkbox" defaultChecked={editing.status === 'REMOVED'}/><span>Retirar este cargo de la cuenta conservando su trazabilidad.</span></label>{formError && <p className="form-error" role="alert">{formError}</p>}<div className="modal-actions"><Button type="button" variant="secondary" onClick={() => setEditing(null)} disabled={Boolean(busy)}>Cancelar</Button><Button type="submit" loading={busy === 'line'}>Guardar corrección</Button></div></form>}</Modal>
    <Modal open={action !== null} onClose={() => {if(!busy) setAction(null);}} title={action === 'ready' ? 'Preparar la cuenta para envío' : action === 'send' ? 'Registrar el envío manual' : 'Registrar respuesta de aseguradora'} description={data.folio}><form onSubmit={e => {e.preventDefault(); const f = new FormData(e.currentTarget); if(action === 'ready') void mutate('ready', {acceptRisk: f.get('acceptRisk') === 'on', reason: String(f.get('reason') || '')}); else if(action === 'send') void mutate('send'); else if(action === 'outcome') void mutate('outcome', {result: f.get('result'), authorizedAmount: Number(f.get('authorizedAmount')), reason: f.get('reason')});}}>{action === 'ready' && <><div className={`notice ${data.lane !== 'GREEN' ? 'notice-warning' : ''}`}><Icon name={data.lane === 'GREEN' ? 'check' : 'alert'}/><p>{data.lane === 'GREEN' ? 'La cuenta quedará disponible para exportar y enviar manualmente desde el portal de la aseguradora.' : 'Esta cuenta conserva hallazgos. Prepararla requiere aceptar expresamente el riesgo y registrar un motivo.'}</p></div>{data.lane !== 'GREEN' && <><Field label="Motivo para continuar con hallazgos" required><textarea name="reason" required minLength={5} maxLength={2000} rows={3}/></Field><label className="checkbox-label"><input type="checkbox" name="acceptRisk" required/><span>Revisé los hallazgos y acepto el riesgo de preparar esta cuenta.</span></label></>}</>}{action === 'send' && <div className="notice"><Icon name="upload"/><p>Confirma que tu equipo ya envió la cuenta por los canales de la aseguradora. Este registro no transmite archivos ni información fuera de Atlas Link.</p></div>}{action === 'outcome' && <><Field label="Resultado" required><select name="result" required><option value="APPROVED">Aprobada</option><option value="ADJUSTED">Aprobada con ajustes</option><option value="REJECTED">Objetada</option></select></Field><Field label="Monto autorizado · MXN" required><input name="authorizedAmount" type="number" min="0" step="0.01" required/></Field><Field label="Motivo o referencia de respuesta" required><textarea name="reason" rows={3} minLength={3} maxLength={2000} required/></Field></>}{formError && <p className="form-error" role="alert">{formError}</p>}<div className="modal-actions"><Button type="button" variant="secondary" disabled={Boolean(busy)} onClick={() => setAction(null)}>Cancelar</Button><Button type="submit" loading={Boolean(busy)}>{action === 'ready' ? 'Preparar cuenta' : action === 'send' ? 'Confirmar envío registrado' : 'Guardar respuesta'}</Button></div></form></Modal>
  </>;
}
