'use client';
import { useState, type FormEvent } from 'react';
import { post, useResource } from '@/lib/api';
import { date, money } from '@/lib/format';
import type { Agreement, Insurer } from '@/lib/types';
import { RoleGate } from './auth';
import AgreementImport from './agreement-import';
import { Button, EmptyState, ErrorState, Field, Icon, Loading, Modal, PageTitle, useToast } from './ui';
type TariffRow = {code: string; price: string; maximum: string; excluded: boolean};
export default function Agreements() {
  const {data, error, loading, reload} = useResource<Agreement[]>('/agreements');
  const {data: insurers} = useResource<Insurer[]>('/insurers');
  const [importOpen,setImportOpen]=useState(false);const [search,setSearch]=useState('');const [create,setCreate]=useState(false);const [selected,setSelected]=useState<Agreement|null>(null);const [publish,setPublish]=useState<Agreement|null>(null);
  const [rows,setRows]=useState<TariffRow[]>([{code:'',price:'',maximum:'',excluded:false}]);const [busy,setBusy]=useState(false);const [formError,setFormError]=useState('');const toast=useToast();
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setFormError('');const f=new FormData(event.currentTarget);const tariffs:Record<string,number>={};const maxQuantities:Record<string,number>={};const excludedCodes:string[]=[];for(const row of rows){const code=row.code.trim().toUpperCase();if(!code)continue;if(row.price!=='')tariffs[code]=Number(row.price);if(row.maximum!=='')maxQuantities[code]=Number(row.maximum);if(row.excluded)excludedCodes.push(code);}try{await post('/agreements',{name:f.get('name'),insurerId:f.get('insurerId'),validFrom:f.get('validFrom'),validTo:f.get('validTo'),rules:{tariffs,maxQuantities,excludedCodes,highRiskThreshold:Number(f.get('highRiskThreshold'))}});setCreate(false);reload();toast('Borrador de convenio guardado. Revísalo antes de publicarlo.');}catch(e){setFormError(e instanceof Error?e.message:'No se pudo crear el convenio.');}finally{setBusy(false);}}
  async function publishAgreement(){if(!publish)return;setBusy(true);setFormError('');try{await post(`/agreements/${publish.id}/publish`,{});setPublish(null);reload();toast('Convenio publicado. Esta versión ya es inmutable.');}catch(e){setFormError(e instanceof Error?e.message:'No se pudo publicar.');}finally{setBusy(false);}}
  const filtered=(data||[]).filter(a=>`${a.name} ${a.insurer}`.toLowerCase().includes(search.toLowerCase()));
  return <RoleGate roles={['HOSPITAL_ADMIN']}><PageTitle title="Convenios y tabuladores"><Button variant="secondary" onClick={()=>setImportOpen(true)}><Icon name="upload" size={17}/> Importar tabulador</Button><Button onClick={()=>{setCreate(true);setRows([{code:'',price:'',maximum:'',excluded:false}]);setFormError('');}}><Icon name="plus" size={17}/> Nuevo convenio</Button></PageTitle><div className="notice"><Icon name="shield"/><p>Cada cuenta conserva la versión del convenio usada en su evaluación. Los convenios publicados no se modifican.</p></div><div className="section-toolbar"><div className="search-input"><Icon name="search" size={18}/><input aria-label="Buscar convenios" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar convenio o aseguradora…"/></div><span>{filtered.length} convenios · demostración</span></div>{loading?<Loading/>:error?<ErrorState message={error} retry={reload}/>:filtered.length?<div className="agreement-grid">{filtered.map(agreement=><article className="panel agreement-card" key={agreement.id}><header><span className="agreement-icon"><Icon name="shield" size={26}/></span><span className={`badge ${agreement.status==='PUBLISHED'?'badge-green':'badge-neutral'}`}>{agreement.status==='PUBLISHED'?'Publicado':'Borrador'}</span></header><p className="eyebrow">{agreement.insurer}</p><h2>{agreement.name}</h2><div className="agreement-version"><span>Versión {agreement.version}</span><span>·</span><span>Convenio demostrativo</span></div><dl><div><dt>Vigencia</dt><dd>{date(agreement.validFrom)} — {date(agreement.validTo)}</dd></div><div><dt>Códigos tabulados</dt><dd>{Object.keys(agreement.rules.tariffs||{}).length}</dd></div><div><dt>Umbral de atención prioritaria</dt><dd>{money(agreement.rules.highRiskThreshold)}</dd></div></dl><footer><Button variant="secondary" onClick={()=>setSelected(agreement)}>Ver reglas <Icon name="arrow" size={16}/></Button>{agreement.status==='DRAFT'&&<Button onClick={()=>{setPublish(agreement);setFormError('');}}>Publicar <Icon name="check" size={16}/></Button>}</footer></article>)}</div>:<EmptyState title="Sin convenios" description="Crea un borrador para configurar tabuladores y validaciones de tu hospital."/>}
    <Modal open={create} onClose={()=>{if(!busy)setCreate(false);}} title="Nuevo convenio" description="Comienza con un borrador. Podrás revisar sus reglas antes de publicarlo." wide><form onSubmit={submit}><div className="form-grid"><Field label="Nombre del convenio" required><input name="name" required maxLength={180} placeholder="Convenio hospitalario 2026"/></Field><Field label="Aseguradora" required><select name="insurerId" required defaultValue=""><option value="" disabled>Selecciona una aseguradora</option>{insurers?.map(i=><option value={i.id} key={i.id}>{i.name}</option>)}</select></Field><Field label="Vigente desde" required><input name="validFrom" type="date" required/></Field><Field label="Vigente hasta" required><input name="validTo" type="date" required/></Field><Field label="Umbral de atención prioritaria · MXN" required className="span-two" hint="Monto de hallazgos a partir del que el convenio requiere revisión prioritaria."><input name="highRiskThreshold" type="number" min="0" step="0.01" defaultValue="10000" required/></Field></div><div className="form-section-title"><h3>Reglas por código</h3><p>Configura únicamente los límites respaldados por el convenio.</p></div><div className="tariff-rows">{rows.map((row,i)=><div className="tariff-row" key={i}><Field label="Código"><input value={row.code} onChange={e=>setRows(rows.map((r,j)=>j===i?{...r,code:e.target.value.toUpperCase()}:r))} placeholder="CONS-01" required maxLength={50}/></Field><Field label="Precio máximo"><input value={row.price} type="number" min="0" step="0.01" onChange={e=>setRows(rows.map((r,j)=>j===i?{...r,price:e.target.value}:r))} placeholder="Sin límite"/></Field><Field label="Cantidad máxima"><input value={row.maximum} type="number" min="0.001" step="0.001" onChange={e=>setRows(rows.map((r,j)=>j===i?{...r,maximum:e.target.value}:r))} placeholder="Sin límite"/></Field><label className="checkbox-label"><input type="checkbox" checked={row.excluded} onChange={e=>setRows(rows.map((r,j)=>j===i?{...r,excluded:e.target.checked}:r))}/>Excluir</label><button className="icon-button" type="button" disabled={rows.length===1} aria-label={`Quitar código ${i+1}`} onClick={()=>setRows(rows.filter((_,j)=>j!==i))}><Icon name="close" size={16}/></button></div>)}</div><Button type="button" variant="secondary" onClick={()=>setRows([...rows,{code:'',price:'',maximum:'',excluded:false}])}><Icon name="plus" size={16}/> Agregar código</Button>{formError&&<p className="form-error" role="alert">{formError}</p>}<div className="modal-actions"><Button type="button" variant="secondary" onClick={()=>setCreate(false)}>Cancelar</Button><Button loading={busy} type="submit">Guardar borrador</Button></div></form></Modal>
    <Modal open={Boolean(selected)} onClose={()=>setSelected(null)} title={selected?.name||'Reglas del convenio'} description={`${selected?.insurer} · Versión ${selected?.version}`} wide>{selected&&<><dl className="detail-facts"><div><dt>Vigencia</dt><dd>{date(selected.validFrom)} — {date(selected.validTo)}</dd></div><div><dt>Umbral prioritario</dt><dd>{money(selected.rules.highRiskThreshold)}</dd></div></dl><div className="table-scroll"><table className="data-table"><thead><tr><th>Código</th><th>Tabulador</th><th>Cantidad máxima</th><th>Cobertura</th></tr></thead><tbody>{Array.from(new Set([...Object.keys(selected.rules.tariffs||{}),...Object.keys(selected.rules.maxQuantities||{}),...(selected.rules.excludedCodes||[])])).map(code=><tr key={code}><td><strong>{code}</strong></td><td>{selected.rules.tariffs[code]===undefined?'Sin regla':money(selected.rules.tariffs[code])}</td><td>{selected.rules.maxQuantities[code]??'Sin regla'}</td><td><span className={`badge ${selected.rules.excludedCodes.includes(code)?'badge-red':'badge-green'}`}>{selected.rules.excludedCodes.includes(code)?'Excluido':'Evaluable'}</span></td></tr>)}</tbody></table></div><p className="subtle-note"><Icon name="shield" size={16}/> Reglas sintéticas de demostración. No representan un contrato comercial real.</p></>}</Modal>
    <Modal open={Boolean(publish)} onClose={()=>{if(!busy)setPublish(null);}} title="Publicar esta versión" description={publish?.name}><div className="notice notice-warning"><Icon name="lock"/><p>Al publicar, esta versión del convenio será inmutable y podrá aplicarse a nuevas evaluaciones dentro de su vigencia.</p></div>{formError&&<p className="form-error" role="alert">{formError}</p>}<div className="modal-actions"><Button variant="secondary" onClick={()=>setPublish(null)}>Volver al borrador</Button><Button loading={busy} onClick={publishAgreement}>Publicar convenio</Button></div></Modal>
    <AgreementImport open={importOpen} onClose={()=>setImportOpen(false)} onCreated={reload} insurers={insurers||[]}/>
  </RoleGate>;
}
