'use client';
import {useRef, useState, type FormEvent} from 'react';
import {api, download} from '@/lib/api';
import {money} from '@/lib/format';
import type {Agreement, Insurer} from '@/lib/types';
import {Button, Field, Icon, Modal, useToast} from './ui';

interface AgreementPreview {
  valid: boolean; checksum: string; rowCount: number;
  errors: {row: number; column: string; message: string}[];
  rules: {tariffs: Record<string, number>; maxQuantities: Record<string, number>; excludedCodes: string[]};
  sample: {code: string; unitPrice: number | null; maxQuantity: number | null; excluded: boolean}[];
}
export default function AgreementImport({open, onClose, onCreated, insurers}: {open: boolean; onClose: () => void; onCreated: () => void; insurers: Insurer[]}) {
  const input = useRef<HTMLInputElement>(null); const toast = useToast();
  const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState<AgreementPreview | null>(null);
  const [busy, setBusy] = useState(''); const [error, setError] = useState('');
  function close() {if(busy) return; setFile(null);setPreview(null);setError('');onClose();}
  function choose(value?: File) {setError('');setPreview(null);setFile(null);if(!value) return;if(!value.name.toLowerCase().endsWith('.xlsx')) {setError('Selecciona un archivo Excel con extensión .xlsx.');return;}if(value.size > 2 * 1024 * 1024) {setError('El archivo supera el límite de 2 MB.');return;}setFile(value);}
  async function template() {setBusy('template');try {await download('/agreements/template','atlas-link-tabulador.xlsx');}catch(e) {setError(e instanceof Error ? e.message : 'No se pudo descargar la plantilla.');}finally {setBusy('');}}
  async function inspect() {if(!file) return;setBusy('preview');setError('');setPreview(null);const body=new FormData();body.append('file',file);try {setPreview(await api<AgreementPreview>('/agreements/preview',{method:'POST',body}));}catch(e) {setError(e instanceof Error ? e.message : 'No se pudo revisar el archivo.');}finally {setBusy('');}}
  async function submit(event: FormEvent<HTMLFormElement>) {event.preventDefault();if(!file || !preview?.valid) return;setBusy('import');setError('');const body=new FormData(event.currentTarget);body.set('file',file);body.set('expectedHash',preview.checksum);try {await api<Agreement>('/agreements/import',{method:'POST',body});setFile(null);setPreview(null);onCreated();onClose();toast('Tabulador importado como borrador. Revisa sus reglas antes de publicar.');}catch(e) {setError(e instanceof Error ? e.message : 'No se pudo importar el convenio.');}finally {setBusy('');}}
  return <Modal open={open} onClose={close} title="Importar un tabulador" description="Revisa el archivo primero. Ninguna regla se publica automáticamente." wide>
    <div className="template-callout"><span className="template-icon"><Icon name="file" size={23}/></span><div><strong>Un código por fila.</strong><p>Precio máximo, cantidad máxima y exclusiones. Hasta 1,000 filas.</p></div><Button variant="ghost" onClick={template} loading={busy==='template'} disabled={Boolean(busy)}><Icon name="download" size={16}/> Plantilla de tabulador</Button></div>
    <div className="notice mt-5"><Icon name="shield"/><p>La vista previa valida todas las filas. Si hay errores, corrige el archivo antes de crear el borrador.</p></div>
    <div className="flex flex-wrap items-center gap-3 mb-5"><input ref={input} type="file" accept=".xlsx" onChange={event=>choose(event.target.files?.[0])} className="sr-only" aria-label="Seleccionar tabulador Excel" tabIndex={-1}/><Button variant="secondary" onClick={()=>input.current?.click()} disabled={Boolean(busy)}><Icon name="upload" size={17}/>{file?'Cambiar tabulador':'Seleccionar tabulador'}</Button><span className="text-sm text-muted break-all">{file?file.name:'Excel .xlsx · Máximo 2 MB'}</span>{file&&!preview?.valid&&<Button onClick={inspect} loading={busy==='preview'} disabled={Boolean(busy)}>Revisar archivo <Icon name="review" size={17}/></Button>}</div>
    {error&&<p className="form-error" role="alert">{error}</p>}
    {preview&&!preview.valid&&<div role="alert"><h3 className="text-base mb-3">Encontramos campos por corregir</h3><div className="table-scroll" tabIndex={0} role="region" aria-label="Errores del tabulador"><table className="data-table"><thead><tr><th>Fila</th><th>Columna</th><th>Qué necesita atención</th></tr></thead><tbody>{preview.errors.map((issue,index)=><tr key={`${issue.row}-${issue.column}-${index}`}><td>{issue.row}</td><td>{issue.column}</td><td>{issue.message}</td></tr>)}</tbody></table></div><p className="text-sm text-muted mt-3">No se ha creado ningún convenio. Vuelve a seleccionar el archivo corregido.</p></div>}
    {preview?.valid&&<form onSubmit={submit}><div className="notice" role="status"><Icon name="check"/><p>{preview.rowCount} filas validadas. {Object.keys(preview.rules.tariffs).length} precios, {Object.keys(preview.rules.maxQuantities).length} límites de cantidad y {preview.rules.excludedCodes.length} exclusiones.</p></div><div className="form-section-title"><h3>Una vista del tabulador</h3><p>Estos códigos forman parte del archivo validado.</p></div><div className="table-scroll mb-6" tabIndex={0} role="region" aria-label="Vista previa del tabulador"><table className="data-table"><thead><tr><th>Código</th><th>Precio máximo</th><th>Cantidad máxima</th><th>Cobertura</th></tr></thead><tbody>{preview.sample.map(row=><tr key={row.code}><td><strong>{row.code}</strong></td><td>{row.unitPrice===null?'Sin regla':money(row.unitPrice)}</td><td>{row.maxQuantity??'Sin regla'}</td><td>{row.excluded?'Excluido':'Evaluable'}</td></tr>)}</tbody></table></div><div className="form-section-title"><h3>El contexto de este convenio</h3><p>El archivo confirmado creará un borrador con estos datos.</p></div><div className="form-grid"><Field label="Nombre del convenio" required><input name="name" required maxLength={180}/></Field><Field label="Aseguradora" required><select name="insurerId" required defaultValue=""><option value="" disabled>Selecciona una aseguradora</option>{insurers.map(insurer=><option key={insurer.id} value={insurer.id}>{insurer.name}</option>)}</select></Field><Field label="Vigente desde" required><input name="validFrom" type="date" required/></Field><Field label="Vigente hasta" required><input name="validTo" type="date" required/></Field><Field label="Umbral de atención prioritaria · MXN" required className="span-two"><input name="highRiskThreshold" type="number" min="0" step="0.01" defaultValue="10000" required/></Field></div><div className="modal-actions"><Button variant="secondary" type="button" onClick={close} disabled={Boolean(busy)}>Cancelar</Button><Button type="submit" loading={busy==='import'} disabled={Boolean(busy)}>Confirmar importación <Icon name="check" size={17}/></Button></div></form>}
  </Modal>;
}
