'use client';
import {useRef, useState, type FormEvent} from 'react';
import {api, download} from '@/lib/api';
import {money} from '@/lib/format';
import {comparisonPalette,lanePalette} from '@/lib/chart-palette';
import type {Agreement, Insurer} from '@/lib/types';
import {DataDistribution} from './data-distribution';
import {DetailsButton,RecordDetailModal} from './record-tools';
import {Button, Field, Icon, Modal, useToast} from './ui';
import s from './operations.module.css';

interface AgreementPreview {
  valid: boolean; checksum: string; rowCount: number;
  errors: {row: number; column: string; message: string}[];
  rules: {tariffs: Record<string, number>; maxQuantities: Record<string, number>; excludedCodes: string[]};
  sample: {code: string; unitPrice: number | null; maxQuantity: number | null; excluded: boolean}[];
}
export default function AgreementImport({open, onClose, onCreated, insurers}: {open: boolean; onClose: () => void; onCreated: () => void; insurers: Insurer[]}) {
  const input = useRef<HTMLInputElement>(null); const toast = useToast();
  const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState<AgreementPreview | null>(null);
  const [selectedIssue,setSelectedIssue]=useState<AgreementPreview['errors'][number]|null>(null);const [selectedSample,setSelectedSample]=useState<AgreementPreview['sample'][number]|null>(null);
  const [busy, setBusy] = useState(''); const [error, setError] = useState('');
  const errorCounts=Array.from((preview?.errors||[]).reduce((counts,issue)=>{counts.set(issue.column,(counts.get(issue.column)||0)+1);return counts;},new Map<string,number>()).entries()).sort((a,b)=>b[1]-a[1]);
  const visibleErrorCounts=errorCounts.slice(0,4).map(([label,value])=>({label,value}));
  const otherErrorCount=errorCounts.slice(4).reduce((sum,item)=>sum+item[1],0);
  const errorDistribution=otherErrorCount>0?[...visibleErrorCounts,{label:'Otras columnas',value:otherErrorCount}]:visibleErrorCounts;
  function close() {if(busy) return; setFile(null);setPreview(null);setError('');onClose();}
  function choose(value?: File) {setError('');setPreview(null);setFile(null);if(!value) return;if(!value.name.toLowerCase().endsWith('.xlsx')) {setError('Selecciona un archivo Excel con extensión .xlsx.');return;}if(value.size > 2 * 1024 * 1024) {setError('El archivo supera el límite de 2 MB.');return;}setFile(value);}
  async function template() {setBusy('template');try {await download('/agreements/template','atlas-link-tabulador.xlsx');}catch(e) {setError(e instanceof Error ? e.message : 'No se pudo descargar la plantilla.');}finally {setBusy('');}}
  async function inspect() {if(!file) return;setBusy('preview');setError('');setPreview(null);const body=new FormData();body.append('file',file);try {setPreview(await api<AgreementPreview>('/agreements/preview',{method:'POST',body}));}catch(e) {setError(e instanceof Error ? e.message : 'No se pudo revisar el archivo.');}finally {setBusy('');}}
  async function submit(event: FormEvent<HTMLFormElement>) {event.preventDefault();if(!file || !preview?.valid) return;setBusy('import');setError('');const body=new FormData(event.currentTarget);body.set('file',file);body.set('expectedHash',preview.checksum);try {await api<Agreement>('/agreements/import',{method:'POST',body});setFile(null);setPreview(null);onCreated();onClose();toast('Tabulador importado como borrador. Revisa sus reglas antes de publicar.');}catch(e) {setError(e instanceof Error ? e.message : 'No se pudo importar el convenio.');}finally {setBusy('');}}
  return <Modal open={open} onClose={close} title="Importar un tabulador" description="Revisa el archivo primero. Ninguna regla se publica automáticamente." wide>
    <div className={s.agreementImport}><div className={s.templateCallout}><span className={s.templateIcon}><Icon name="file" size={23}/></span><div><strong>Un código por fila.</strong><p>Precio máximo, cantidad máxima y exclusiones. Hasta 1,000 filas.</p></div><Button variant="ghost" onClick={template} loading={busy==='template'} disabled={Boolean(busy)}><Icon name="download" size={16}/> Plantilla de tabulador</Button></div>
    <div className="notice mt-5"><Icon name="shield"/><p>La vista previa valida todas las filas. Si hay errores, corrige el archivo antes de crear el borrador.</p></div>
    <div className="flex flex-wrap items-center gap-3 mb-5"><input ref={input} type="file" accept=".xlsx" onChange={event=>choose(event.target.files?.[0])} className="sr-only" aria-label="Seleccionar tabulador Excel" tabIndex={-1}/><Button variant="secondary" onClick={()=>input.current?.click()} disabled={Boolean(busy)}><Icon name="upload" size={17}/>{file?'Cambiar tabulador':'Seleccionar tabulador'}</Button><span className="text-sm text-muted break-all">{file?file.name:'Excel .xlsx · Máximo 2 MB'}</span>{file&&!preview?.valid&&<Button onClick={inspect} loading={busy==='preview'} disabled={Boolean(busy)}>Revisar archivo <Icon name="review" size={17}/></Button>}</div>
    {error&&<p className="form-error" role="alert">{error}</p>}
    {preview&&!preview.valid&&<div role="alert"><h3 className="text-base mb-3">Encontramos campos por corregir</h3><div className="table-scroll" tabIndex={0} role="region" aria-label="Errores del tabulador"><table className="data-table"><thead><tr><th>Fila</th><th>Columna</th><th>Detalle</th></tr></thead><tbody>{preview.errors.map((issue,index)=><tr key={`${issue.row}-${issue.column}-${index}`}><td>{issue.row}</td><td>{issue.column}</td><td><DetailsButton label={`error en fila ${issue.row}`} onClick={()=>setSelectedIssue(issue)}/></td></tr>)}</tbody></table></div><div className={s.importDistribution}><DataDistribution title="Errores por columna" scope={`${preview.errors.length} errores detectados en la vista previa`} caption="Errores agrupados por columna en el archivo revisado" values={errorDistribution.map((item,index)=>({label:item.label,value:item.value,color:comparisonPalette[index%comparisonPalette.length]}))}/></div><p className="text-sm text-muted mt-3">No se ha creado ningún convenio. Vuelve a seleccionar el archivo corregido.</p></div>}
    {preview?.valid&&<form onSubmit={submit}><div className="notice" role="status"><Icon name="check"/><p>{preview.rowCount} filas validadas. {Object.keys(preview.rules.tariffs).length} precios, {Object.keys(preview.rules.maxQuantities).length} límites de cantidad y {preview.rules.excludedCodes.length} exclusiones.</p></div><div className="form-section-title"><h3>Una vista del tabulador</h3><p>Estos códigos forman parte de la muestra del archivo validado.</p></div><div className={s.importDistribution}><DataDistribution title="Cobertura en la muestra" scope={`${preview.sample.length} códigos incluidos en la vista previa · ${preview.rowCount} filas en el archivo completo`} caption="Muestra del tabulador agrupada por cobertura" values={[{label:'Evaluable',value:preview.sample.filter(row=>!row.excluded).length,color:lanePalette.GREEN},{label:'Excluido',value:preview.sample.filter(row=>row.excluded).length,color:lanePalette.RED}]}/></div><div className="table-scroll mb-6" tabIndex={0} role="region" aria-label="Muestra del tabulador"><table className="data-table"><thead><tr><th>Código</th><th>Cobertura</th><th>Detalle</th></tr></thead><tbody>{preview.sample.map(row=><tr key={row.code}><td><strong>{row.code}</strong></td><td>{row.excluded?'Excluido':'Evaluable'}</td><td><DetailsButton label={`código ${row.code}`} onClick={()=>setSelectedSample(row)}/></td></tr>)}</tbody></table></div><div className="form-section-title"><h3>El contexto de este convenio</h3><p>El archivo confirmado creará un borrador con estos datos.</p></div><div className="form-grid"><Field label="Nombre del convenio" required><input name="name" required maxLength={180}/></Field><Field label="Aseguradora" required><select name="insurerId" required defaultValue=""><option value="" disabled>Selecciona una aseguradora</option>{insurers.map(insurer=><option key={insurer.id} value={insurer.id}>{insurer.name}</option>)}</select></Field><Field label="Vigente desde" required><input name="validFrom" type="date" required/></Field><Field label="Vigente hasta" required><input name="validTo" type="date" required/></Field><Field label="Umbral de atención prioritaria · MXN" required className="span-two"><input name="highRiskThreshold" type="number" min="0" step="0.01" defaultValue="10000" required/></Field></div><div className="modal-actions"><Button variant="secondary" type="button" onClick={close} disabled={Boolean(busy)}>Cancelar</Button><Button type="submit" loading={busy==='import'} disabled={Boolean(busy)}>Confirmar importación <Icon name="check" size={17}/></Button></div></form>}
    <RecordDetailModal open={Boolean(selectedIssue)} onClose={()=>setSelectedIssue(null)} title={`Error en fila ${selectedIssue?.row??''}`} description={selectedIssue?.column||'Detalle de validación'} fields={selectedIssue?[{label:'Fila',value:selectedIssue.row},{label:'Columna',value:selectedIssue.column},{label:'Qué necesita atención',value:selectedIssue.message}]:[]}/>
    <RecordDetailModal open={Boolean(selectedSample)} onClose={()=>setSelectedSample(null)} title={`Código ${selectedSample?.code??''}`} description="Regla incluida en la muestra visible" fields={selectedSample?[{label:'Precio máximo · MXN',value:selectedSample.unitPrice===null?'Sin regla':money(selectedSample.unitPrice)},{label:'Cantidad máxima',value:selectedSample.maxQuantity??'Sin regla'},{label:'Cobertura',value:selectedSample.excluded?'Excluido':'Evaluable'}]:[]}/>
  </div></Modal>;
}
