'use client';
import { useState, type FormEvent } from 'react';
import { post, useResource } from '@/lib/api';
import { date, money } from '@/lib/format';
import type { Agreement, Insurer } from '@/lib/types';
import { RoleGate } from './auth';
import AgreementImport from './agreement-import';
import {comparisonPalette} from '@/lib/chart-palette';
import {DataDistribution} from './data-distribution';
import {DetailsButton,RecordDetailModal} from './record-tools';
import tools from './record-tools.module.css';
import { Button, EmptyState, ErrorState, Field, Icon, Loading, Modal, PageTitle, useToast } from './ui';
import s from './operations.module.css';
type TariffRow = {code: string; price: string; maximum: string; excluded: boolean};
export default function Agreements() {
  const {data, error, loading, reload} = useResource<Agreement[]>('/agreements');
  const {data: insurers} = useResource<Insurer[]>('/insurers');
  const [importOpen,setImportOpen]=useState(false);const [search,setSearch]=useState('');const [create,setCreate]=useState(false);const [selected,setSelected]=useState<Agreement|null>(null);const [selectedRule,setSelectedRule]=useState<string|null>(null);const [publish,setPublish]=useState<Agreement|null>(null);
  const [rows,setRows]=useState<TariffRow[]>([{code:'',price:'',maximum:'',excluded:false}]);const [busy,setBusy]=useState(false);const [formError,setFormError]=useState('');const toast=useToast();
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setFormError('');const f=new FormData(event.currentTarget);const tariffs:Record<string,number>={};const maxQuantities:Record<string,number>={};const excludedCodes:string[]=[];for(const row of rows){const code=row.code.trim().toUpperCase();if(!code)continue;if(row.price!=='')tariffs[code]=Number(row.price);if(row.maximum!=='')maxQuantities[code]=Number(row.maximum);if(row.excluded)excludedCodes.push(code);}try{await post('/agreements',{name:f.get('name'),insurerId:f.get('insurerId'),validFrom:f.get('validFrom'),validTo:f.get('validTo'),rules:{tariffs,maxQuantities,excludedCodes,highRiskThreshold:Number(f.get('highRiskThreshold'))}});setCreate(false);reload();toast('Borrador de convenio guardado. Revísalo antes de publicarlo.');}catch(e){setFormError(e instanceof Error?e.message:'No se pudo crear el convenio.');}finally{setBusy(false);}}
  async function publishAgreement(){if(!publish)return;setBusy(true);setFormError('');try{await post(`/agreements/${publish.id}/publish`,{});setPublish(null);reload();toast('Convenio publicado. Esta versión ya es inmutable.');}catch(e){setFormError(e instanceof Error?e.message:'No se pudo publicar.');}finally{setBusy(false);}}
  const filtered=(data||[]).filter(a=>`${a.name} ${a.insurer}`.toLowerCase().includes(search.toLowerCase()));
  return <RoleGate roles={['HOSPITAL_ADMIN']}><div className={s.agreementsPage}><PageTitle title="Convenios y tabuladores"><Button variant="secondary" onClick={()=>setImportOpen(true)}><Icon name="upload" size={17}/> Importar tabulador</Button><Button onClick={()=>{setCreate(true);setRows([{code:'',price:'',maximum:'',excluded:false}]);setFormError('');}}><Icon name="plus" size={17}/> Nuevo convenio</Button></PageTitle><div className={s.policyNotice}><Icon name="shield"/><p>Cada cuenta conserva la versión del convenio usada en su evaluación. Los convenios publicados no se modifican.</p></div><div className={s.agreementToolbar}><label className={s.searchControl}><Icon name="search" size={18}/><input aria-label="Buscar convenios" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar convenio o aseguradora…"/></label><span>{filtered.length} convenios · demostración</span></div>{!loading&&!error&&filtered.length>0&&<div className={s.agreementDistribution}><DataDistribution title="Convenios por estado" scope={`${filtered.length} convenios visibles después de la búsqueda`} caption="Convenios agrupados por estado en el resultado visible" values={([{key:'PUBLISHED',label:'Publicado',color:comparisonPalette[0]},{key:'DRAFT',label:'Borrador',color:comparisonPalette[2]}] as const).map(item=>({label:item.label,value:filtered.filter(agreement=>agreement.status===item.key).length,color:item.color}))}/></div>}{loading?<Loading/>:error?<ErrorState message={error} retry={reload}/>:filtered.length?<><p className={s.tableScrollHint}>Desliza la tabla para consultar los convenios.</p><div className={`${s.tableRegion} ${s.agreementTableRegion}`} tabIndex={0} role="region" aria-label="Convenios y vigencias"><table className={`data-table ${tools.compactTable}`}><thead><tr><th scope="col">Convenio</th><th scope="col">Estado</th><th scope="col">Vigencia</th><th scope="col">Versión</th><th scope="col">Detalle</th><th scope="col">Acción</th></tr></thead><tbody>{filtered.map(agreement=><tr key={agreement.id}><td><strong title={`${agreement.name} · ${agreement.insurer}`}>{agreement.name}</strong></td><td><span className={`badge ${agreement.status==='PUBLISHED'?'badge-green':'badge-neutral'}`}>{agreement.status==='PUBLISHED'?'Publicado':'Borrador'}</span></td><td>{date(agreement.validFrom)} — {date(agreement.validTo)}</td><td>{agreement.version}</td><td><DetailsButton label={agreement.name} onClick={()=>setSelected(agreement)}/></td><td>{agreement.status==='DRAFT'&&<Button onClick={()=>{setPublish(agreement);setFormError('');}}>Publicar <Icon name="check" size={15}/></Button>}</td></tr>)}</tbody></table></div></>:<EmptyState title="Sin convenios" description="Crea un borrador para configurar tabuladores y validaciones de tu hospital."/>}
    <Modal open={create} onClose={()=>{if(!busy)setCreate(false);}} title="Nuevo convenio" description="Comienza con un borrador. Podrás revisar sus reglas antes de publicarlo." wide><form onSubmit={submit}><div className="form-grid"><Field label="Nombre del convenio" required><input name="name" required maxLength={180} placeholder="Convenio hospitalario 2026"/></Field><Field label="Aseguradora" required><select name="insurerId" required defaultValue=""><option value="" disabled>Selecciona una aseguradora</option>{insurers?.map(i=><option value={i.id} key={i.id}>{i.name}</option>)}</select></Field><Field label="Vigente desde" required><input name="validFrom" type="date" required/></Field><Field label="Vigente hasta" required><input name="validTo" type="date" required/></Field><Field label="Umbral de atención prioritaria · MXN" required className="span-two" hint="Monto de hallazgos a partir del que el convenio requiere revisión prioritaria."><input name="highRiskThreshold" type="number" min="0" step="0.01" defaultValue="10000" required/></Field></div><div className="form-section-title"><h3>Reglas por código</h3><p>Configura únicamente los límites respaldados por el convenio.</p></div><div className="tariff-rows">{rows.map((row,i)=><div className="tariff-row" key={i}><Field label="Código"><input value={row.code} onChange={e=>setRows(rows.map((r,j)=>j===i?{...r,code:e.target.value.toUpperCase()}:r))} placeholder="CONS-01" required maxLength={50}/></Field><Field label="Precio máximo"><input value={row.price} type="number" min="0" step="0.01" onChange={e=>setRows(rows.map((r,j)=>j===i?{...r,price:e.target.value}:r))} placeholder="Sin límite"/></Field><Field label="Cantidad máxima"><input value={row.maximum} type="number" min="0.001" step="0.001" onChange={e=>setRows(rows.map((r,j)=>j===i?{...r,maximum:e.target.value}:r))} placeholder="Sin límite"/></Field><label className="checkbox-label"><input type="checkbox" checked={row.excluded} onChange={e=>setRows(rows.map((r,j)=>j===i?{...r,excluded:e.target.checked}:r))}/>Excluir</label><button className="icon-button" type="button" disabled={rows.length===1} aria-label={`Quitar código ${i+1}`} onClick={()=>setRows(rows.filter((_,j)=>j!==i))}><Icon name="close" size={16}/></button></div>)}</div><Button type="button" variant="secondary" onClick={()=>setRows([...rows,{code:'',price:'',maximum:'',excluded:false}])}><Icon name="plus" size={16}/> Agregar código</Button>{formError&&<p className="form-error" role="alert">{formError}</p>}<div className="modal-actions"><Button type="button" variant="secondary" onClick={()=>setCreate(false)}>Cancelar</Button><Button loading={busy} type="submit">Guardar borrador</Button></div></form></Modal>
    <Modal open={Boolean(selected)} onClose={()=>{setSelected(null);setSelectedRule(null);}} title={selected?.name||'Reglas del convenio'} description={`${selected?.insurer} · Versión ${selected?.version}`} wide>{selected&&<><dl className="detail-facts"><div><dt>Vigencia</dt><dd>{date(selected.validFrom)} — {date(selected.validTo)}</dd></div><div><dt>Umbral prioritario</dt><dd>{money(selected.rules.highRiskThreshold)}</dd></div></dl>{(()=>{const codes=Array.from(new Set([...Object.keys(selected.rules.tariffs||{}),...Object.keys(selected.rules.maxQuantities||{}),...(selected.rules.excludedCodes||[])]));const excluded=codes.filter(code=>selected.rules.excludedCodes.includes(code)).length;return <><div className={s.agreementDistribution}><DataDistribution title="Cobertura de códigos" scope={`${codes.length} códigos conservados en la versión ${selected.version}`} caption="Códigos de tabulador agrupados por cobertura" values={[{label:'Evaluable',value:codes.length-excluded,color:comparisonPalette[0]},{label:'Excluido',value:excluded,color:comparisonPalette[4]}]}/></div><div className="table-scroll"><table className={`data-table ${tools.compactTable}`}><thead><tr><th>Código</th><th>Cobertura</th><th>Detalle</th></tr></thead><tbody>{codes.map(code=><tr key={code}><td><strong>{code}</strong></td><td><span className={`badge ${selected.rules.excludedCodes.includes(code)?'badge-red':'badge-green'}`}>{selected.rules.excludedCodes.includes(code)?'Excluido':'Evaluable'}</span></td><td><DetailsButton label={`código ${code}`} onClick={()=>setSelectedRule(code)}/></td></tr>)}</tbody></table></div></>;})()}<p className="subtle-note"><Icon name="shield" size={16}/> Reglas sintéticas de demostración. No representan un contrato comercial real.</p></>}</Modal>
    <RecordDetailModal open={Boolean(selected&&selectedRule)} onClose={()=>setSelectedRule(null)} title={selectedRule?`Código ${selectedRule}`:'Detalle de regla'} description={selected?.name} fields={selected&&selectedRule?[{label:'Cobertura',value:selected.rules.excludedCodes.includes(selectedRule)?'Excluido':'Evaluable'},{label:'Precio máximo · MXN',value:selected.rules.tariffs[selectedRule]===undefined?'Sin regla':money(selected.rules.tariffs[selectedRule])},{label:'Cantidad máxima',value:selected.rules.maxQuantities[selectedRule]??'Sin regla'}]:[]}/>
    <Modal open={Boolean(publish)} onClose={()=>{if(!busy)setPublish(null);}} title="Publicar esta versión" description={publish?.name}><div className="notice notice-warning"><Icon name="lock"/><p>Al publicar, esta versión del convenio será inmutable y podrá aplicarse a nuevas evaluaciones dentro de su vigencia.</p></div>{formError&&<p className="form-error" role="alert">{formError}</p>}<div className="modal-actions"><Button variant="secondary" onClick={()=>setPublish(null)}>Volver al borrador</Button><Button loading={busy} onClick={publishAgreement}>Publicar convenio</Button></div></Modal>
    <AgreementImport open={importOpen} onClose={()=>setImportOpen(false)} onCreated={reload} insurers={insurers||[]}/>
  </div></RoleGate>;
}
