#!/bin/sh
set -eu
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" \
  --set=idpw="$IDENTITY_PASSWORD" --set=idowner="$IDENTITY_OWNER_PASSWORD" \
  --set=ctrlpw="$CONTROL_PASSWORD" --set=ctrlowner="$CONTROL_OWNER_PASSWORD" \
  --set=hosppw="$HOSPITAL_PASSWORD" --set=hospowner="$HOSPITAL_OWNER_PASSWORD" <<'SQL'
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE ROLE atlas_identity LOGIN PASSWORD :'idpw' NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS;
CREATE ROLE atlas_identity_owner LOGIN PASSWORD :'idowner' NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS;
CREATE ROLE atlas_control LOGIN PASSWORD :'ctrlpw' NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS;
CREATE ROLE atlas_control_owner LOGIN PASSWORD :'ctrlowner' NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS;
CREATE ROLE atlas_hospital LOGIN PASSWORD :'hosppw' NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS;
CREATE ROLE atlas_hospital_owner LOGIN PASSWORD :'hospowner' NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS;
GRANT CREATE ON DATABASE atlas_link TO atlas_identity_owner,atlas_control_owner,atlas_hospital_owner;
CREATE SCHEMA identity AUTHORIZATION atlas_identity_owner;
CREATE SCHEMA control AUTHORIZATION atlas_control_owner;
CREATE SCHEMA hospital AUTHORIZATION atlas_hospital_owner;
SQL
